### ISSUE TITLE
eztrans로 번역을 선택하고 실행하면 오류가 일어납니다

### ISSUE THREAD

**Issue by saihd** [ttop32/mangaJOCR#4]
download done
progess
  0%|          | 0/10 [00:00<?, ?it/s]Exception in thread Thread-5:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "manga_translator.py", line 97, in processTranslationTask
  File "text_translate.py", line 39, in translate
  File "text_translate.py", line 16, in translateList
  File "text_translate.py", line 26, in translateEztrans
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 957, in _execute_child
FileNotFoundError: [WinError 2] 지정된 파일을 찾을 수 없습니다

google ocr 과 eztrans 를 사용하였을때 이런 오류가 계속 일어납니다

**Comment by saihd** [comment]
download done
progess
  0%|          | 0/10 [00:00<?, ?it/s]Exception in thread Thread-10:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "manga_translator.py", line 97, in processTranslationTask
  File "text_translate.py", line 39, in translate
  File "text_translate.py", line 16, in translateList
  File "text_translate.py", line 26, in translateEztrans
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 957, in _execute_child
OSError: [WinError 225] 파일에 바이러스 또는 기타 사용자 동의 없이 설치된 소프트웨어가 있기 때문에 작업이 완료되지 않았 습니다
이런 것도 뜨더군요 물론 방화벽을 해제하면 해결되니 큰 문제는 아닙니다만

**Comment by ttop32** [comment]
File "text_translate.py", line 26, in translateEztrans 에서 


JMTrans/lib_/ez_trans.exe 를 실행을 실행시키고
해당 프로그램이 eztrans xp ehnd dll인 C:\Program Files (x86)\ChangShinSoft\ezTrans XP\J2KEngineH.dll 을 실행시키는데

에러 문에서는 해당 파일이 없다고 뜨는거로 봐서는
JMTrans/lib_/ez_trans.exe랑
C:\Program Files (x86)\ChangShinSoft\ezTrans XP\J2KEngineH.dll 둘다 존재하는지 봐주시겠어요?
안티바이러스같은거는 신경 안쓰고 만들어서 혹시 삭제되지않았나해서요

저도 한동안 안써서 다시 실행해보기는 할게요
